const RELATIONSHIPS = {
  PARENT: 'Parent',
  SIBLING: 'Sibling',
  CHILD: 'Child',
  SPOUSE: 'Spouse',
  EX_SPOUSE: 'Ex-Spouse',
  LIFE_PARTNER: 'Life Partner',
  GRANDPARENT: 'Grandparent',
  GRANDCHILD: 'Grandchild',
  AUNT: 'Aunt',
  UNCLE: 'Uncle',
  NIECE: 'Niece',
  NEPHEW: 'Nephew',
  COUSIN: 'Cousin',
  STEPPARENT: 'Stepparent',
  STEPCHILD: 'Stepchild',
  PARENT_IN_LAW: 'Parent-in-law',
  SIBLING_IN_LAW: 'Sibling-in-law',
  CHILD_IN_LAW: 'Child-in-law',
  OTHER_RELATIVE: 'Other relative',
  OTHER_DEPENDENT: 'Other dependent',
};
export default RELATIONSHIPS;
