export const bankColorNames = {
  'Bank of America': 'bankOfAmerica',
  'Capital One': 'capitalOne',
  'Chase Bank': 'chase',
  Citi: 'citibank',
  'Wells Fargo': 'wellsFargo',
  'TD Bank': 'td',
  Fidelity: 'fidelity',
  Prudential: 'prudential',
  'Merrill Lynch': 'merrillLynch',
  'Charles Schwab': 'charlesSchwab',
  'TD Ameritrade': 'td',
  Vanguard: 'vanguard',
  Simple: 'simple',
  Ally: 'ally',
  'Bank of Internet': 'bankOfInternet',
  'US Bank': 'USBank',
};
